name: Release

on:
  push:
    branches:
      - main
      - "v[0-9]+.[0-9]+"
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"

    - name: Install dependencies
      run: go mod download

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
