name: Release

on:
  push:
    branches:
      - main
      - "v[0-9]+.[0-9]+"
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"

    - name: Install dependencies
      run: go mod download

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release --clean ${{ github.ref == 'refs/heads/main' && '--snapshot' || '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: create GitHub release (canary)
      if: github.ref == 'refs/heads/main'
      run: |
        gh release delete canary --cleanup-tag
        gh release create canary dist/test-app*.tar.gz \
          --title canary \
          --prerelease \
          --notes-file - <<- EOF
          This is a "canary" release of the most recent commits on our main branch. Canary is **not stable**.
          It is only intended for developers wishing to try out the latest features in Spin, some of which may not be fully implemented.
        EOF
      env:
        GH_TOKEN: ${{ github.token }}
